### ISSUE TITLE
olist.db não disponível

### ISSUE THREAD

**Issue by rodrafanas** [TeoCalvo/olist-ml-models#105]
Por favor poderia disponibilizar um novo link para fazer o download do olist.db ? Na aula do Twitch o link disponiblizado não está mais funcionando.
https://drive.google.com/file/d/1rhY6J6l-Zx5Zsl3wDLLJsH7TbnGqTme7/view

**Comment by francismelojr** [comment]
Segue o link para baixar o arquivo

https://drive.google.com/drive/folders/1xu8tMqhzrLCAEgj5pr6hhcAHv9BBD5jF?usp=sharing
